### ISSUE TITLE
prevent a user from defining mon as target and as extra monitor in a cluster

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-installer#131]
[admin@gregmeno-clot-2 ~]$ cat mon_configure 
    {
        "calamari": false,
        "conf": {"global": {"auth supported": "cephx"}},
        "host": "gregmeno-clot-2.localdomain",
        "interface": "eth0",
        "fsid": "deedcb4c-a67a-4997-93a6-92149ad2622a",
        "monitor_secret": "AQA7P8dWAAAAABAAH/tbiZQn/40Z8pr959UmEA==",
        "cluster_name": "ceph",
        "cluster_network": "172.16.115.238/24",
        "public_network": "172.16.115.238/24",
        "monitors": [{"host": "gregmeno-clot-2", "interface": "eth0"}],
        "redhat_storage": true,
        "verbose": false
    }
    
    
    
    request:
    curl -d @mon_configure -H "Content-Type: application/json" http://gregmeno-clot-1:8181/api/mon/configure/
    
    
    
    
    
    /var/log/messages on installer node
    [ceph.ceph-common | generate ceph configuration file] ******************* \nfatal: [gregmeno-clot-2] => One or more undefined variables: \'dict object\' has no attribute \'ansible_eth0\'\n\nFATAL: all hosts have already failed -- aborting\n\nPLAY RECAP ******************************************************************** \n           to retry, use: --limit @/var/lib/ceph-installer/site.sample.retry\n\ngregmeno-clot-2            : ok=26   changed=2    unreachable=1    failed=0   \ngregmeno-clot-2.localdomain : ok=0    changed=0    unreachable=1    failed=0   \n\n', '2016-04-18 14:41:37.136771', 0, 3, 13)
    

Here the user provided the same mon as the target and in the `"monitors"` key. The installer should prevent this from hapenning

**Comment by alfredodeza** [comment]
@andrewschoen do you feel like the installer should prevent this? or is this something that should be handled (and ignored) by ceph-ansible?

**Comment by ktdreyer** [comment]
For what it's worth, this did introduce some complexity into my client library. Here's the function that configures a list of monitors via `/api/mon/configure`:

```
-def _monitors_payload(mon_hosts):
-    return map(lambda host: {'host': host, 'interface': 'eth0'}, mon_hosts)
+def _monitors_payload(mon_hosts, exclude=None):
+    data = []
+    for host in mon_hosts:
+        if host != exclude:
+            data.append({'host': host, 'interface': 'eth0'})
+    return data
 
 def configure_mons(mon_hosts, base_url):
     url = posixpath.join(base_url, 'api/mon/configure/')
-    monitors = _monitors_payload(mon_hosts)
     for ip in mon_hosts:
         payload = {
             'host': ip,
             'interface': 'eth0',
             'fsid': 'deedcb4c-a67a-4997-93a6-92149ad2622a',
             'monitor_secret': 'AQA7P8dWAAAAABAAH/tbiZQn/40Z8pr959UmEA==',
             'cluster_network': '172.16.0.0/12',
             'public_network': '172.16.0.0/12',
-            'monitors': monitors,
             'redhat_storage': False,
         }
+        monitors = _monitors_payload(mon_hosts, ip)
+        if len(monitors) > 0:
+            payload['monitors'] = monitors
         post(url, payload)

```
