### ISSUE TITLE
Documentation to install and configure ceph-installer in Fedora

### ISSUE THREAD

**Issue by kmkanagaraj** [ceph/ceph-installer#162]
Please provide a step-by-step instructions to install and configure ceph-installer in Fedora.

**Comment by ktdreyer** [comment]
@tserlin , are you working on packaging this for Fedora?

**Comment by tserlin** [comment]
I'm on this, yes.

Thomas

----- Original Message -----

**Comment by kmkanagaraj** [comment]
Any update on this?

**Comment by alfredodeza** [comment]
This project is no longer maintained
