### ISSUE TITLE
cannot find keyrings /api/osd/configure

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-installer#53]
PLAY ***************************************************************************
    
    TASK [setup] *******************************************************************
    ok: [192.168.111.101]
    
    TASK [ceph-fetch-keys : find ceph keys] ****************************************
    fatal: [192.168.111.101]: FAILED! => {"changed": false, "cmd": "ls -1 /etc/ceph/*.keyring", "delta": "0:00:00.002033", "end": "2016-02-19 13:03:02.771527", "failed": true, "rc": 2, "start": "2016-02-19 13:03:02.769494", "stderr": "ls: cannot access /etc/ceph/*.keyring: No such file or directory", "stdout": "", "stdout_lines": [], "warnings": []}
    
    PLAY RECAP *********************************************************************
    192.168.111.101            : ok=1    changed=0    unreachable=0    failed=1

**Comment by andrewschoen** [comment]
This looks like you're running it against a node that's not configured as a monitor.
