### ISSUE TITLE
api/osd/configure needs to know about each monitors interface

### ISSUE THREAD

**Issue by andrewschoen** [ceph/ceph-installer#56]
Currently ``monitor_interface`` is a string, this needs to change so that we can know about each monitors interface because they may vary between monitors.

- will need to be able to set vars for specific hosts, most likely in the inventory

**Comment by alfredodeza** [comment]
I would propose something like:

    "monitors": [
        {"host": "mon1.example.com", "interface": "eth1", ... },
        {"host": "mon2.example.com", "interface": "eth1", ... }
    ]

**Comment by andrewschoen** [comment]
fixed with https://github.com/ceph/ceph-installer/pull/74
