### ISSUE TITLE
no $HOME environment variable

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-installer#58]
Breaks situations where ansible depends on it. Mostly when it expands to write to temporary files that usually go into `$HOME/.ansible/tmp` which gets 'expanded' to `/.ansible/tmp` that doesn't exist and is owned by root

Bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1312441

**Comment by andrewschoen** [comment]
This is fixed now, no?

**Comment by ktdreyer** [comment]
Not in systemd...
